### ISSUE TITLE
Fuzzy-entropy-based-optimal-thresholding

### ISSUE THREAD

**Issue by 1251757818** [Deepaknkumar/Fuzzy-entropy-based-optimal-thresholding#1]
Dear Author, your code is for color image, but i want to deal grayscale image, It is wrong. Can you tell me how to deal with it? i use color image to test, find it's result is different with a paper(Bat algorithm Fuzzy entropy), so i want to try grayscale image

**Comment by Deepaknkumar** [comment]
Hi, the code in this repository does not belong to any paper. If you want to use for grayscale images, you may need to do some modifications in the source_code20* file in each of the heuristics folders.
Hope that helps. Please let me know if you have further questions.

**Comment by 1251757818** [comment]
Dear Author, I want to use the code to realize the paper(http://or.nsfc.gov.cn/bitstream/00001903-5/253738/1/1000014212368.pdf) result. So i use the paper test image to try, the result is different with the paper. The paper idear is the same with you, i can't find the bug. Can you help me? thank you!
